# Web-appendix-continuous-time-TMLE
* Welcome

This is the web-appendix of our manuscript entitled 
/Continuous-time targeted minimum loss-based estimation of estimation of intervention-specific mean outcomes./

=[[provide link to arXiv]]=

This repository provides the R-codes behind our empirical studies for
proof-of-concept so that anonymous users can reproduce the results.

Note that we here do not (yet) provide user-friendly code which
implements our method in a computational efficient way ... but we are
currently working hard on achieving exactly this. Stay tuned! 

The current implementation requires a large memory for simulations of
many time points. 

Below we describe the simulation scenario in terms of the actual
R-code. 

* Running the code

The following code uses one computing core to calculate the estimates
of conTMLE and LTMLE using a single simulated dataset. The code that
produces the empirical results of Table 1 and Table 2 of the
manuscript are shown længer down.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
# NOTE: you need to set the working directory 
source("./examples/load.R")
K5.conTMLE <- runTMLE(no_cores=1,K=5,misspecify.init = FALSE,M = 1,n = 1000,seed=23,progress.bar=-1)
K5.conTMLE
#+END_SRC

#+RESULTS[<2020-11-11 10:48:36> 1f6f9e60188dc96dcada7ce6ff7cfe123a2267dd]:
:    conTMLE.A0      se.A0   init.A0 se.init.A0 conTMLE.A1      se.A1   init.A1 se.init.A1
: 1:  0.5305897 0.03168532 0.5069958 0.03172444  0.4241032 0.02574778 0.4129555 0.02576413

#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
# NOTE: you need to set the working directory 
source("./examples/load.R")
K5.ltmle <- runLTMLE(no_cores=1,K=5,misspecify.init = FALSE,M = 1,n = 1000,seed=23,progress.bar=-1)
K5.ltmle
#+END_SRC

#+RESULTS[<2020-11-10 17:36:09> f43f9656ddcdd88083218be5cebf6ea917011a36]:
: 
: Estimating psi with LTMLE based on observed data:
:     ltmle.A0      sd.A0  ltmle.A1      sd.A1
: 1: 0.5252997 0.03648988 0.4207659 0.02741637

* Making of tables 1 and 2

** Table 1

We provide code that produces results for =K=5= and =K=30= for LTMLE
and our new method, conTMLE. The code in files [[examples/table1.R]] and
[[examples/table2.R]] generate the following results:

#+BEGIN_SRC R  :results output raw drawer  :exports both  :session *R* :cache yes  
#+END_SRC

*** K=5
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
source("./examples/load.R")
table1.K5.true <- readRDS(file="./examples/table1-K5-true.rds")
table1.K5.ltmle <- readRDS(file="./examples/table1-K5-ltmle.rds")
table1.K5.conTMLE <- readRDS(file="./examples/table1-K5-conTMLE.rds")
## table1.K5.conTMLE <- table1.K5.conTMLE[sample(1:1000,size=200,replace=FALSE)]
## class(table1.K5.conTMLE) <- "watmle"
summary(object=table1.K5.ltmle,true=table1.K5.true)
summary(object=table1.K5.conTMLE,true=table1.K5.true)
#+END_SRC

#+RESULTS[<2020-11-11 06:45:21> a80f575221ddbaa98b856dfc8b1b69488182a22a]:
#+begin_example
     LTMLE       A0       A1       psi
1     true 0.559494 0.424656  0.134838
2     mean 0.560405 0.424974 -0.135430
3     bias 0.000911 0.000318  0.000592
4       se 0.038240 0.029796  0.048478
5 coverage 0.974000 0.951000  0.969000
6      MSE 0.034042 0.028738  0.042971
     conTMLE       A0       A1       psi
1     true 0.559494 0.424656  0.134838
2     mean 0.560441 0.425019 -0.135422
3     bias 0.000947 0.000363  0.000584
4       se 0.030199 0.024911  0.039148
5 coverage 0.941000 0.923000  0.939000
6      MSE 0.031565 0.027283  0.040191
#+end_example

*** K=30
#+BEGIN_SRC R  :results output :exports both  :session *R* :cache yes  
source("./examples/load.R")
table1.K30.true <- readRDS(file="./examples/table1-K30-true.rds")
table1.K30.ltmle <- readRDS(file="./examples/table1-K30-ltmle.rds")
table1.K30.conTMLE <- readRDS(file="./examples/table1-K30-conTMLE.rds")
summary(object=table1.K30.ltmle,true=table1.K30.true)
summary(object=table1.K30.conTMLE,true=table1.K30.true)
#+END_SRC

#+RESULTS[<2020-11-11 06:42:08> 915f2184a5660e5f680b7c37671a10c87251a998]:
#+begin_example
     LTMLE      A0      A1     psi
1     true 0.61191 0.47326  0.1387
2     mean 0.61598 0.48202 -0.1340
3     bias 0.00406 0.00876 -0.0047
4       se 0.08108 0.06812  0.1059
5 coverage 0.97600 0.96700  0.9710
6      MSE 0.06371 0.06047  0.0870
     conTMLE       A0        A1       psi
1     true  0.61191  0.473262  0.138652
2     mean  0.61020  0.472410 -0.137794
3     bias -0.00171 -0.000852 -0.000858
4       se  0.04366  0.036767  0.057076
5 coverage  0.93700  0.947000  0.954000
6      MSE  0.04496  0.037248  0.058023
#+end_example

** Table 2

*** K=30 (misspecified initial estimator)
#+BEGIN_SRC R  :results output   :exports both  :session *R* :cache yes  
source("./examples/load.R")
table2.K30.true <- readRDS(file="./examples/table1-K30-true.rds")
table2.K30.misspecified <- readRDS(file="./examples/table2-K30-conTMLE.rds")
summary(object=table2.K30.misspecified,true=table2.K30.true)
#+END_SRC

#+RESULTS[<2020-11-11 06:36:42> ea82779657abf9a862e8686c263c1d4fd0ca6cfa]:
:      conTMLE       A0        A1      psi
: 1     true  0.61191  0.473262  0.13865
: 2     mean  0.60904  0.472868 -0.13617
: 3     bias -0.00287 -0.000394 -0.00248
: 4       se  0.04369  0.036876  0.05717
: 5 coverage  0.93900  0.941000  0.95200
: 6      MSE  0.04519  0.037545  0.05824

* Changing the simulation scenario

The current simulation setting is best described with the following
R-code:

#+BEGIN_SRC R  :results output raw drawer  :exports code  :session *R* :cache yes  
# Step 1: baseline covariate 
L0 <- sample(1:6, n, replace=1000)/6
# Step 2: baseline treatment
form.A0 <- function(L0){
  cbind(-0.1+0.25*L0)
}
# Step 3: covariate monitoring process: time for current measurement 
#         depends on previous measurements (X.prev)
form.dN.L <- function(L0, dN.L.prev, L.prev, A.prev){
  -0.2-0.05*K-0.025*(K>7)-0.25*dN.L.prev-0.15*L0-0.1*(A.prev==1)+0.3*L.prev
}
# Step 4: treatment monitoring process: time for current measurement 
#         depends on time of last measurement (X.prev)
form.dN.A <- function(L0, dN.A.prev, L.prev, A.prev, no.jumps.A, L.star){
  -0.75-0.05*K-0.42*dN.A.prev+0.15*L0+0.3*(A.prev==2)+0.4*(A.prev==1)-0.25*L.prev
}
form.C <- function(L0, L.prev, A.prev, A0){
  -3.95+(K>40)*5-0.4*K^{2/3}-0.24*(K>2 & K<=4)-0.4*(K>4 & K<=9)
  -(K>9)*0.4*K^{1/5}+0.2*(K>25)*K^{1/4}
  +0.1*L0+0.2*(A0==1)+0.9*(A0==2)+2.15*L.prev
}
form.L <- function(L0, L.prev, A.prev, A0){
  0.5-0.4*A0+0.15*L0-0.25*(A.prev==1)+0.4*L.prev
}
form.A <- function(L0, L.prev, A.prev, A0){
  cbind(-1+(1-A0)*0.6+(1-A.prev)*0.4+L.prev*0.6-0.15*(K>15)*L.prev)
}
form.Y <- function(L0, L.prev, A.prev, A0, no.jumps.A, dN.A.prev) {
  -1.1-0.33*K/3*(K>2 & K<=4)-0.25*K^{2/3}-0.25*(K>4 & K<=9)-
    (K>25 & K<45)*0.3*K^{1/5}-
      (K>75)*0.31+(K>85)*0.2-
      (K>25 & K<75)*0.5*K^{1/5}+0.6*(K>25)*K^{1/4}-0.25*A.prev+
      0.4*L.prev-0.25*A0+0.35*L.prev*A0+(K>75)*0.1*A0+(K>85)*0.01*A0
}
#+END_SRC

*  Dependencies 

** R-version

The code has been tested with the following R version

#+BEGIN_SRC R  :results output :exports results  :session *R* :cache yes  
version
#+END_SRC

#+RESULTS[<2020-11-09 18:12:47> 143b9cabc93679f20607ffef9eeb3eadefba88c3]:
#+begin_example
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          0.2                         
year           2020                        
month          06                          
day            22                          
svn rev        78730                       
language       R                           
version.string R version 4.0.2 (2020-06-22)
nickname       Taking Off Again
#+end_example

and the following package versions:

#+BEGIN_SRC R  :results output raw drawer  :exports results  :session *R* :cache yes  
pp <- c("data.table", "zoo", "stringr", "ltmle", "parallel", "foreach", "doParallel")
Publish::org(data.table(Package=pp,Version=sapply(pp,function(x) as.character(packageVersion(x)))))
#+END_SRC

#+RESULTS[<2020-11-09 18:13:13> ec9009aff7db8031012c07b48c3be553f0446e14]:
:results:
| Package    | Version |
|------------+---------|
| data.table |  1.13.0 |
| zoo        |   1.8.8 |
| stringr    |   1.4.0 |
| ltmle      |   1.2.0 |
| parallel   |   4.0.2 |
| foreach    |   1.5.0 |
| doParallel |  1.0.15 |
:end:

